# Generated by Django 5.0.4 on 2024-05-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
        ("listings", "0001_initial"),
        ("realtors", "0001_initial"),
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reports",
            new_name="Report",
        ),
    ]
